################################
# Direct dependencies

# See "Gopkg.lock"

################################

################################
# Transitive dependencies, and overrides

[[override]]
  name = "google.golang.org/genproto"
  source = "https://github.com/google/go-genproto"
  revision = "09f6ed296fc66555a25fe4ce95173148778dfa85"

[[override]]
  name = "golang.org/x/sys"
  source = "https://github.com/golang/sys"
  revision = "ebfc5b4631820b793c9010c87fd8fef0f39eb082"

[[override]]
  name = "golang.org/x/text"
  source = "https://github.com/golang/text"
  revision = "b19bf474d317b857955b12035d2c5acb57ce8b01"

[[override]]
  name = "github.com/gorilla/websocket"
  source = "https://github.com/gorilla/websocket"
  revision = "4201258b820c74ac8e6922fc9e6b52f71fe46f8d"

[[override]]
  name = "gopkg.in/yaml.v2"
  source = "https://github.com/go-yaml/yaml"
  revision = "cd8b52f8269e0feb286dfeef29f8fe4d5b397e0b"

[[override]]
  name = "github.com/cpuguy83/go-md2man"
  source = "https://github.com/cpuguy83/go-md2man"
  revision = "23709d0847197db6021a51fdb193e66e9222d4e7"

[[override]]
  name = "github.com/russross/blackfriday"
  source = "https://github.com/russross/blackfriday"
  revision = "4048872b16cc0fc2c5fd9eacf0ed2c2fedaa0c8c"

[[override]]
  name = "github.com/prometheus/common"
  source = "https://github.com/prometheus/common"
  revision = "e3fb1a1acd7605367a2b378bc2e2f893c05174b7"

[[override]]
  name = "github.com/prometheus/procfs"
  source = "https://github.com/prometheus/procfs"
  revision = "a6e9df898b1336106c743392c48ee0b71f5c4efa"

[[override]]
  name = "github.com/beorn7/perks"
  source = "https://github.com/beorn7/perks"
  revision = "4c0e84591b9aa9e6dcfdf3e020114cd81f89d5f9"

[[override]]
  name = "github.com/sirupsen/logrus"
  source = "https://github.com/sirupsen/logrus"
  version = "=v1.0.3"

[[override]]
  name = "github.com/mattn/go-runewidth"
  source = "https://github.com/mattn/go-runewidth"
  version = "=v0.0.2"

################################
