language: go

install: go get -t -v ./...

script: go test -v ./...

matrix:
  include:
    - name: "go1.11.x"
      go: 1.11.x
      gobuild_args: -v
    - name: "go1.12.x"
      go: 1.12.x
      gobuild_args: -v
    - name: "go1.12.x race"
      go: 1.12.x
      gobuild_args: -v -race

notifications:
  email:
    recipients:
      - peter@cockroachlabs.com
    on_success: never
    on_failure: always
